[profile.default]
src = 'contracts'
out = 'foundry-out'
libs = ['lib']
solc_version = '0.8.19'
optimizer_runs = 800
via_ir = false
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./foundry-out"}]

[profile.ci]
fuzz_runs = 100000
